/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    pages: Page;
    faqs: Faq;
    'stuff-posts': StuffPost;
    'buy-cards': BuyCard;
    'email-phrases': EmailPhrase;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'stuff-posts': StuffPostsSelect<false> | StuffPostsSelect<true>;
    'buy-cards': BuyCardsSelect<false> | BuyCardsSelect<true>;
    'email-phrases': EmailPhrasesSelect<false> | EmailPhrasesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  slug: string;
  description?: string | null;
  bullets?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Price in cents (e.g. 2900 = $29.00)
   */
  price?: number | null;
  /**
   * Primary product image shown in product cards and product detail page.
   */
  mainImage?: (string | null) | Media;
  /**
   * Additional product images used in the expandable gallery preview.
   */
  galleryImages?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy image list. Prefer using Main Image + Gallery Images for new content.
   */
  images?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Medusa product ID. Get this from Medusa admin → Products → [product] → Variants.
   */
  medusaId?: string | null;
  /**
   * Medusa variant ID. Get this from Medusa admin → Products → [product] → Variants.
   */
  variantId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  hero?: {
    heading?: string | null;
    subheading?: string | null;
    image?: (string | null) | Media;
  };
  sections?:
    | {
        type?: ('text' | 'products' | 'faq' | 'email-signup') | null;
        heading?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * FAQ items shown on the homepage. Add, remove, or reorder freely.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  /**
   * The question text shown in the accordion header.
   */
  question: string;
  /**
   * The answer. Supports bold, italic, and links (underlined automatically).
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Lower numbers appear first. Use 10, 20, 30... to leave room.
   */
  order?: number | null;
  /**
   * Uncheck to hide this FAQ without deleting it.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cards shown in the "Stuff we’ve done" section on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stuff-posts".
 */
export interface StuffPost {
  id: string;
  /**
   * Small pill label shown at the top. Example: "Black Friday 2018".
   */
  tag: string;
  /**
   * Main headline text. Example: "Holy fuck we had some deals."
   */
  label: string;
  /**
   * Square illustration (1080×1080 recommended). Appears floating on the card.
   */
  image: string | Media;
  /**
   * Where the card links when clicked. Example: /blog/black-friday
   */
  href?: string | null;
  /**
   * Label shown beside the arrow button.
   */
  cta?: ('Read' | 'Watch' | 'Listen' | 'Play') | null;
  /**
   * Card background color (hex). Example: #fffe5b, #ede5ff, #1b5bff
   */
  backgroundColor?: string | null;
  /**
   * Main headline text color. Example: #fe2f2f, #7333f1, #d7b73b
   */
  textColor?: string | null;
  /**
   * Background color of the tag pill.
   */
  tagBg?: string | null;
  /**
   * Text color inside the tag pill.
   */
  tagColor?: string | null;
  /**
   * Display order. Lower numbers appear first. Use 10, 20, 30...
   */
  order?: number | null;
  /**
   * Uncheck to hide this card without deleting it.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cards in the "Buy it now" horizontal scroll. Each card has floating product images, headline text and a CTA button.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buy-cards".
 */
export interface BuyCard {
  id: string;
  /**
   * Main headline. Use \n for line breaks. E.g. "For whatever\nyou're into."
   */
  label: string;
  /**
   * Button label. E.g. "Buy $5 Packs", "Find Out", "Buy Now"
   */
  cta: string;
  /**
   * Link for the entire card and button. E.g. /products/hot-box
   */
  href?: string | null;
  /**
   * Card background color (hex or CSS color). E.g. #FFB3D9, #90EE90, #FF7043
   */
  backgroundColor: string;
  /**
   * Check if background is dark — makes text and button white instead of black.
   */
  darkBackground?: boolean | null;
  /**
   * 1–3 product images floating on the card. Position them independently for a "scattered" look like the reference.
   */
  images?:
    | {
        image: string | Media;
        /**
         * CSS top value. E.g. "-5%", "10px", "20%". Negative values let image bleed out of card.
         */
        top?: string | null;
        /**
         * CSS right value. E.g. "0%", "-10px".
         */
        right?: string | null;
        /**
         * Width of this image relative to card. E.g. "55%", "300px".
         */
        width?: string | null;
        /**
         * Rotation in degrees (-45 to 45). Negative = tilts left, positive = tilts right.
         */
        rotation?: number | null;
        /**
         * Stack order when images overlap. Higher = on top.
         */
        zIndex?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Display order — lower numbers appear first in the scroll.
   */
  order?: number | null;
  /**
   * Uncheck to hide without deleting.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The rotating phrases in the email section headline. E.g. "we chop up a Picasso,"
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-phrases".
 */
export interface EmailPhrase {
  id: string;
  /**
   * The rotating phrase. Should end with a comma. E.g. "we chop up a Picasso,"
   */
  phrase: string;
  /**
   * Controls rotation order. Lower = appears earlier.
   */
  order?: number | null;
  /**
   * Uncheck to pause this phrase from appearing.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'stuff-posts';
        value: string | StuffPost;
      } | null)
    | ({
        relationTo: 'buy-cards';
        value: string | BuyCard;
      } | null)
    | ({
        relationTo: 'email-phrases';
        value: string | EmailPhrase;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  price?: T;
  mainImage?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  medusaId?: T;
  variantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        image?: T;
      };
  sections?:
    | T
    | {
        type?: T;
        heading?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stuff-posts_select".
 */
export interface StuffPostsSelect<T extends boolean = true> {
  tag?: T;
  label?: T;
  image?: T;
  href?: T;
  cta?: T;
  backgroundColor?: T;
  textColor?: T;
  tagBg?: T;
  tagColor?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buy-cards_select".
 */
export interface BuyCardsSelect<T extends boolean = true> {
  label?: T;
  cta?: T;
  href?: T;
  backgroundColor?: T;
  darkBackground?: T;
  images?:
    | T
    | {
        image?: T;
        top?: T;
        right?: T;
        width?: T;
        rotation?: T;
        zIndex?: T;
        id?: T;
      };
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-phrases_select".
 */
export interface EmailPhrasesSelect<T extends boolean = true> {
  phrase?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteTitle?: string | null;
  footerText?: string | null;
  footerLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  navLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls all text content on the homepage. FAQs, Buy Cards, Stuff Posts, and Email Phrases are managed in their own Collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  /**
   * Hero section — the full-screen card animation.
   */
  hero?: {
    /**
     * Rotating press quotes shown bottom-left of the hero. They cycle with the card sets.
     */
    quotes?:
      | {
          /**
           * Include quotes. E.g. "Hysterical."
           */
          quote: string;
          /**
           * Publication name. E.g. TIME
           */
          source: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The white "about" section below the hero.
   */
  about?: {
    /**
     * Large bold paragraph — the main description.
     */
    paragraph1?: string | null;
    /**
     * Smaller second paragraph.
     */
    paragraph2?: string | null;
  };
  /**
   * The "Buy the game." scroll section heading. Cards are managed in the Buy Cards collection.
   */
  buySection: {
    heading: string;
  };
  /**
   * The white "Steal the game." section.
   */
  stealSection: {
    heading: string;
    /**
     * First paragraph body text.
     */
    body?: string | null;
    /**
     * Second paragraph (the disclaimer).
     */
    body2?: string | null;
    /**
     * PDF download URL for both buttons.
     */
    downloadUrl?: string | null;
    /**
     * Text inside the starburst badge. Use \n for line breaks.
     */
    badgeText?: string | null;
  };
  /**
   * The dark "Stuff we've done." section. Cards are managed in the Stuff Posts collection.
   */
  stuffSection: {
    heading: string;
    /**
     * Text inside the starburst badge top-right of the section.
     */
    badgeText?: string | null;
  };
  /**
   * The email sign-up section. Rotating phrases are managed in the Email Phrases collection.
   */
  emailSection?: {
    /**
     * Text before the rotating phrase.
     */
    headingPrefix?: string | null;
    /**
     * Text after the rotating phrase.
     */
    headingSuffix?: string | null;
    disclaimer?: string | null;
    /**
     * Placeholder text in the email input box.
     */
    placeholder?: string | null;
  };
  /**
   * FAQ section settings. Individual questions are managed in the FAQs collection.
   */
  faqSection: {
    heading: string;
  };
  /**
   * Footer content.
   */
  footer?: {
    copyright?: string | null;
    /**
     * Links in the Shop column.
     */
    shopLinks?:
      | {
          label: string;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Links in the Info column.
     */
    infoLinks?:
      | {
          label: string;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Links in the Find Us column.
     */
    findUsLinks?:
      | {
          label: string;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Legal links in the footer bottom bar.
     */
    legalLinks?:
      | {
          label: string;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  footerText?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        quotes?:
          | T
          | {
              quote?: T;
              source?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        paragraph1?: T;
        paragraph2?: T;
      };
  buySection?:
    | T
    | {
        heading?: T;
      };
  stealSection?:
    | T
    | {
        heading?: T;
        body?: T;
        body2?: T;
        downloadUrl?: T;
        badgeText?: T;
      };
  stuffSection?:
    | T
    | {
        heading?: T;
        badgeText?: T;
      };
  emailSection?:
    | T
    | {
        headingPrefix?: T;
        headingSuffix?: T;
        disclaimer?: T;
        placeholder?: T;
      };
  faqSection?:
    | T
    | {
        heading?: T;
      };
  footer?:
    | T
    | {
        copyright?: T;
        shopLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        infoLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        findUsLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        legalLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}